# Generated by Django 3.0.5 on 2020-04-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='Publishing date')),
                ('pic_url', models.CharField(max_length=200)),
            ],
        ),
    ]
